name: Doxygen Docs

on:
  push:
    branches:
      - master

permissions:
      pages: write
      id-token: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
