name: Doxygen Docs

on:
  push:
    branches:
      - master

permissions:
      pages: write
      id-token: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Prepare clean artifact
        run: |
          mkdir docs/html_clean
          rsync -a --no-links docs/html/ docs/html_clean/
      
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/html_clean

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
